//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P2k7.Api.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.7.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://projects.fujinet.vn/_vti_bin/psi/admin.asmx")]
        public string P2k7_Api_AdminWebSvc_Admin {
            get {
                return ((string)(this["P2k7_Api_AdminWebSvc_Admin"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://projects.fujinet.vn/_vti_bin/psi/archive.asmx")]
        public string P2k7_Api_ArchiveWebSvc_Archive {
            get {
                return ((string)(this["P2k7_Api_ArchiveWebSvc_Archive"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://projects.fujinet.vn/_vti_bin/psi/calendar.asmx")]
        public string P2k7_Api_CalendarWebSvc_Calendar {
            get {
                return ((string)(this["P2k7_Api_CalendarWebSvc_Calendar"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://projects.fujinet.vn/_vti_bin/psi/customfields.asmx")]
        public string P2k7_Api_CustomfieldsWebSvc_CustomFields {
            get {
                return ((string)(this["P2k7_Api_CustomfieldsWebSvc_CustomFields"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://projects.fujinet.vn/_vti_bin/psi/events.asmx")]
        public string P2k7_Api_EventsWebSvc_Events {
            get {
                return ((string)(this["P2k7_Api_EventsWebSvc_Events"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://projects.fujinet.vn/_vti_bin/psi/loginforms.asmx")]
        public string P2k7_Api_LoginformsWebSvc_LoginForms {
            get {
                return ((string)(this["P2k7_Api_LoginformsWebSvc_LoginForms"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://projects.fujinet.vn/_vti_bin/psi/loginwindows.asmx")]
        public string P2k7_Api_LoginwindowsWebSvc_LoginWindows {
            get {
                return ((string)(this["P2k7_Api_LoginwindowsWebSvc_LoginWindows"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://projects.fujinet.vn/_vti_bin/psi/Lookuptable.asmx")]
        public string P2k7_Api_LookuptableWebSvc_LookupTable {
            get {
                return ((string)(this["P2k7_Api_LookuptableWebSvc_LookupTable"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://projects.fujinet.vn/_vti_bin/psi/project.asmx")]
        public string P2k7_Api_ProjectWebSvc_Project {
            get {
                return ((string)(this["P2k7_Api_ProjectWebSvc_Project"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://projects.fujinet.vn/_vti_bin/psi/queuesystem.asmx")]
        public string P2k7_Api_QueuesystemWebSvc_QueueSystem {
            get {
                return ((string)(this["P2k7_Api_QueuesystemWebSvc_QueueSystem"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://projects.fujinet.vn/_vti_bin/psi/resource.asmx")]
        public string P2k7_Api_ResourceWebSvc_Resource {
            get {
                return ((string)(this["P2k7_Api_ResourceWebSvc_Resource"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://projects.fujinet.vn/_vti_bin/psi/security.asmx")]
        public string P2k7_Api_SecurityWebSvc_Security {
            get {
                return ((string)(this["P2k7_Api_SecurityWebSvc_Security"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://projects.fujinet.vn/_vti_bin/psi/statusing.asmx")]
        public string P2k7_Api_StatusingWebSvc_Statusing {
            get {
                return ((string)(this["P2k7_Api_StatusingWebSvc_Statusing"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://projects.fujinet.vn/_vti_bin/psi/timesheet.asmx")]
        public string P2k7_Api_TimesheetWebSvc_TimeSheet {
            get {
                return ((string)(this["P2k7_Api_TimesheetWebSvc_TimeSheet"]));
            }
        }
    }
}
